
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Suporte\Documents\GitHub\inventario\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#29263A")


canvas = Canvas(
    window,
    bg = "#29263A",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked (impressão)"),
    relief="flat"
)
button_1.place(
    x=805.0,
    y=139.0,
    width=224.0,
    height=81.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    background='#f0f0f0',
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked (histórico)"),
    relief="flat"
)
button_2.place(
    x=546.0,
    y=139.0,
    width=224.0,
    height=81.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked (procurar)"),
    relief="flat"
)
button_3.place(
    x=287.0,
    y=139.0,
    width=224.0,
    height=81.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_4 = Button(
    background = 'red',
    text = 'Gerenciar', 
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked (gerenciar)"),
    relief="flat"
)

button_4.place(
    
    x=28.0,
    y=139.0,
    width=224.0,
    height=81.0
)

canvas.create_rectangle(
    28.0,
    210.0,
    1414.0,
    985.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    12.0,
    36.0,
    anchor="nw",
    text="Inventário T.I. DEART",
    fill="#D9D9D9",
    font=("Inter Black", 40 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    1340.0,
    61.0,
    image=image_image_1
)

canvas.create_text(
    1210.0,
    1000.0,
    anchor="nw",
    text="@Marcela; @Filipe; @Vinicius",
    fill="#9B9B9B",
    font=("Inter Black", 12 * -1)
)

canvas.create_text(
    74.0,
    273.0,
    anchor="nw",
    text="Tombo:",
    fill="#000000",
    font=("Inter SemiBold", 24 * -1)
)

canvas.create_text(
    74.0,
    860.0,
    anchor="nw",
    text="Tombo:",
    fill="#000000",
    font=("Inter SemiBold", 24 * -1)
)

canvas.create_text(
    74.0,
    348.0,
    anchor="nw",
    text="Item:",
    fill="#000000",
    font=("Inter SemiBold", 24 * -1)
)

canvas.create_text(
    74.0,
    423.0,
    anchor="nw",
    text="Sala:",
    fill="#000000",
    font=("Inter SemiBold", 24 * -1)
)

canvas.create_rectangle(
    43.0,
    726.0,
    1354.0003662109375,
    729.0,
    fill="#000000",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    533.5,
    874.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=177.0,
    y=853.0,
    width=713.0,
    height=41.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    533.5,
    287.5,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=177.0,
    y=266.0,
    width=713.0,
    height=41.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    533.5,
    362.5,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=177.0,
    y=341.0,
    width=713.0,
    height=41.0
)

canvas.create_rectangle(
    177.0,
    416.0,
    313.0,
    459.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    287.0,
    416.0,
    313.0,
    459.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    299.0000040911227,
    440.0,
    300.88353106234604,
    442.49994542254535,
    fill="#000000",
    outline="")

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=1102.0,
    y=844.0,
    width=210.0,
    height=61.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=1102.0,
    y=598.0,
    width=210.0,
    height=61.0
)
window.resizable(False, False)
window.mainloop()
