-- MySQL Script generated by MySQL Workbench
-- Fri Apr 12 10:10:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `HISTORICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HISTORICO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `HISTORICO` (
  `idHistorico` INT NOT NULL AUTO_INCREMENT,
  `itemID` CHAR(10) NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `SalaOrigemID` VARCHAR(3) NOT NULL,
  `SalaDestinoID` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idHistorico`))
  FOREIGN KEY (itemID) REFERENCES ITENS(tombo),
  FOREIGN KEY (SalaOrigemID) REFERENCES SALAS(sala),
  FOREIGN KEY (SalaDestinoID) REFERENCES SALAS(sala)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ITENS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITENS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ITENS` (
  `tombo` CHAR(10) NULL,
  `objeto` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `idSala` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`tombo`, `HISTORICO_idHistorico`))
  FOREIGN KEY (idSala) REFERENCES SALAS(sala)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SALAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SALAS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SALAS` (
  `sala` VARCHAR(3) NOT NULL,
  `descricao` BINARY(1) NOT NULL,
  `predio` BINARY(1) NULL,
  PRIMARY KEY (`sala`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
